name: MPP
on: [push]
jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        ocaml-version: [ '4.06.1', '4.07.0', '4.08.1', '4.09.0' ]
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@master
    - uses: avsm/setup-ocaml@master
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Dune-shims
      run: opam install -y dune stdlib-shims
    - name: Build
      run: opam exec -- dune build
